name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-core.txt
          pip install gunicorn

      - name: Create static files
        run: |
          echo 'from dashboard import app
          app.index_string = """
          <!DOCTYPE html>
          <html>
              <head>
                  {%metas%}
                  <title>Houston Astros Analytics Dashboard</title>
                  {%favicon%}
                  {%css%}
              </head>
              <body>
                  {%app_entry%}
                  <footer>
                      {%config%}
                      {%scripts%}
                      {%renderer%}
                  </footer>
              </body>
          </html>
          """
          app.run_server(debug=False)' > serve.py
          python serve.py &
          sleep 5
          curl http://127.0.0.1:8050/ > index.html
          pkill -f "python serve.py"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 